// <auto-generated />
using Compro_Intern.Daaataaa;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Compro_Intern.Migrations
{
    [DbContext(typeof(IntContext))]
    partial class IntContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Compro_Intern.Models.IntDesg", b =>
                {
                    b.Property<int>("DesgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesgName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesgRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DesgId");

                    b.ToTable("Desgs");
                });

            modelBuilder.Entity("Compro_Intern.Models.IntRec", b =>
                {
                    b.Property<int>("RecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RecAdd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecPhn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecId");

                    b.ToTable("Recs");
                });

            modelBuilder.Entity("Compro_Intern.Models.IntReql", b =>
                {
                    b.Property<int>("LId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LId");

                    b.ToTable("Ls");
                });

            modelBuilder.Entity("Compro_Intern.Models.IntStat", b =>
                {
                    b.Property<int>("SId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IntId")
                        .HasColumnType("int");

                    b.HasKey("SId");

                    b.ToTable("Sts");
                });

            modelBuilder.Entity("Compro_Intern.Models.IntWhr", b =>
                {
                    b.Property<int>("HId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CHr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IHr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HId");

                    b.ToTable("Hrs");
                });

            modelBuilder.Entity("Compro_Intern.Models.RegInt", b =>
                {
                    b.Property<int>("RegIntId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IntAddr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntAge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntNu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntPas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RegIntId");

                    b.ToTable("Regs");
                });
#pragma warning restore 612, 618
        }
    }
}
